# Generated by Django 3.2 on 2021-04-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_sectionowned_lessonowned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionowned',
            name='lessonOwned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lessonowned'),
        ),
        migrations.AlterField(
            model_name='sectionowned',
            name='quizOwned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.quizowned'),
        ),
    ]
