# Generated by Django 3.2 on 2021-04-28 11:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210428_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
