# Generated by Django 3.2 on 2021-04-29 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_training_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseowned',
            name='lastQuiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.quiz'),
        ),
        migrations.AlterField(
            model_name='courseowned',
            name='lastLesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
    ]
