# Generated by Django 3.2 on 2021-04-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20210429_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='quiz 1', max_length=50),
            preserve_default=False,
        ),
    ]
