# Generated by Django 3.2 on 2021-04-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_quiz_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseowned',
            name='sectionOwned',
        ),
        migrations.AddField(
            model_name='courseowned',
            name='sectionOwned',
            field=models.ManyToManyField(blank=True, to='course.SectionOwned'),
        ),
        migrations.RemoveField(
            model_name='lessonowned',
            name='stepOwned',
        ),
        migrations.AddField(
            model_name='lessonowned',
            name='stepOwned',
            field=models.ManyToManyField(blank=True, to='course.StepOwned'),
        ),
        migrations.RemoveField(
            model_name='sectionowned',
            name='lessonOwned',
        ),
        migrations.AddField(
            model_name='sectionowned',
            name='lessonOwned',
            field=models.ManyToManyField(blank=True, to='course.LessonOwned'),
        ),
        migrations.RemoveField(
            model_name='sectionowned',
            name='quizOwned',
        ),
        migrations.AddField(
            model_name='sectionowned',
            name='quizOwned',
            field=models.ManyToManyField(blank=True, to='course.QuizOwned'),
        ),
    ]
