# Generated by Django 3.2 on 2021-04-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20210429_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='estimateTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='stepowned',
            name='timeConsume',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
