# Generated by Django 3.2 on 2021-04-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20210429_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='description',
        ),
        migrations.AddField(
            model_name='step',
            name='timeMinimum',
            field=models.TimeField(default='00:20:00'),
            preserve_default=False,
        ),
    ]
