# Generated by Django 3.2 on 2021-04-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JWTAuth', '0001_initial'),
        ('course', '0011_auto_20210429_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='totalParticipant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='totalRating',
            field=models.ManyToManyField(blank=True, to='JWTAuth.Employee'),
        ),
    ]
