# Generated by Django 3.2 on 2021-04-29 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20210429_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseowned',
            name='lastStep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.step'),
        ),
    ]
