# Generated by Django 3.2 on 2021-04-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_courseowned_laststep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='type',
        ),
        migrations.AddField(
            model_name='course',
            name='totalStepAndQuiz',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='courseowned',
            name='totalComplete',
            field=models.FloatField(default=0),
        ),
    ]
