# Generated by Django 3.2 on 2021-05-01 08:11

from django.db import migrations, models
import django.db.models.deletion
'''
'''

class Migration(migrations.Migration):

    dependencies = [
        ('JWTAuth', '0001_initial'),
        ('course', '0015_auto_20210429_1840'),
    ]

    operations = []
