# Generated by Django 3.2 on 2021-05-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20210501_1511'),
    ]

    operations = []
