# Generated by Django 3.2 on 2021-05-01 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20210501_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsectionowned',
            name='quizSection',
        ),
    ]
