# Generated by Django 3.2 on 2021-05-01 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_remove_quizsectionowned_quizsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsectionowned',
            name='quizSection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.quizsection'),
        ),
    ]
