# Generated by Django 3.2 on 2021-05-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_quizsectionowned_quizsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsectionowned',
            name='quizOwned',
            field=models.ManyToManyField(blank=True, null=True, to='course.QuizOwned'),
        ),
    ]
