# Generated by Django 3.2 on 2021-05-01 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_quizsectionowned_quizowned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseowned',
            name='lastQuiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.quizsection'),
        ),
    ]
