# Generated by Django 3.2 on 2021-05-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_alter_courseowned_lastquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsectionowned',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
