# Generated by Django 3.2 on 2021-05-06 03:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JWTAuth', '0003_alter_employee_start_work_date'),
        ('course', '0021_alter_course_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 10, 38, 34, 183149)),
        ),
        migrations.CreateModel(
            name='HourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseowned')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JWTAuth.employee')),
            ],
        ),
    ]
