# Generated by Django 3.2 on 2021-05-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_quizsectionowned_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsection',
            name='quiz',
        ),
    ]
