# Generated by Django 3.2 on 2021-05-06 03:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JWTAuth', '0004_alter_employee_start_work_date'),
        ('course', '0023_auto_20210506_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 6, 10, 56, 12, 152074))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseowned')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JWTAuth.employee')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 10, 56, 12, 125146)),
        ),
        migrations.DeleteModel(
            name='HourseAccess',
        ),
    ]
