# Generated by Django 3.2 on 2021-05-06 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20210506_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseowned',
            name='dateJoined',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 11, 22, 51, 600941)),
        ),
        migrations.AlterField(
            model_name='accesstime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 11, 22, 51, 603932)),
        ),
        migrations.AlterField(
            model_name='course',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 11, 22, 51, 587977)),
        ),
    ]
