# Generated by Django 3.2 on 2021-05-08 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_auto_20210508_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstime',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 20, 58, 25, 38751)),
        ),
        migrations.AlterField(
            model_name='course',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 20, 58, 25, 15814)),
        ),
        migrations.AlterField(
            model_name='courseowned',
            name='dateJoined',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 20, 58, 25, 34761)),
        ),
    ]
