# Generated by Django 3.2 on 2021-05-05 04:04

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JWTAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='test department', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='employee',
            name='posistion',
            field=models.CharField(default='test position', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='start_work_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 11, 4, 15, 434850)),
        ),
    ]
