# Generated by Django 3.2 on 2021-05-06 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JWTAuth', '0002_auto_20210505_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_work_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 10, 38, 34, 119319)),
        ),
    ]
