# Generated by Django 3.2 on 2021-05-06 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JWTAuth', '0003_alter_employee_start_work_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_work_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 10, 56, 12, 64309)),
        ),
    ]
