# Generated by Django 3.2 on 2021-05-08 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JWTAuth', '0004_alter_employee_start_work_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_work_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 20, 20, 9, 191321)),
        ),
    ]
