# Generated by Django 3.2 on 2021-04-23 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JWTAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_owner', to='JWTAuth.employee')),
                ('upvote', models.ManyToManyField(to='JWTAuth.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('question', models.TextField(max_length=500)),
                ('total_answer', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2021, 4, 23, 15, 49, 40, 868658))),
                ('answer', models.ManyToManyField(to='forum.Answer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_owner', to='JWTAuth.employee')),
                ('topic', models.ManyToManyField(to='forum.Topic')),
                ('upvote', models.ManyToManyField(to='JWTAuth.Employee')),
            ],
        ),
    ]
