# Generated by Django 3.2 on 2021-04-23 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JWTAuth', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='total_answer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='upvote',
            field=models.ManyToManyField(blank=True, to='JWTAuth.Employee'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='answer',
            field=models.ManyToManyField(blank=True, to='forum.Answer'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 16, 19, 12, 765243)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='topic',
            field=models.ManyToManyField(blank=True, to='forum.Topic'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='upvote',
            field=models.ManyToManyField(blank=True, to='JWTAuth.Employee'),
        ),
    ]
