# Generated by Django 3.2 on 2021-04-23 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210423_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 0, 36, 11, 299296)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 0, 36, 11, 287327)),
        ),
    ]
