# Generated by Django 3.2 on 2021-05-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20210501_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='linkUrl',
        ),
        migrations.RemoveField(
            model_name='training',
            name='location',
        ),
        migrations.RemoveField(
            model_name='training',
            name='method',
        ),
        migrations.AddField(
            model_name='schedule',
            name='linkUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='method',
            field=models.IntegerField(blank=True, choices=[(0, 'Online'), (0, 'Offline')], null=True),
        ),
    ]
