# Generated by Django 3.2 on 2021-05-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20210501_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='endTime',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startTime',
            field=models.DateTimeField(default=0),
        ),
    ]
