# Generated by Django 3.2 on 2021-05-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_training_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comptency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training')),
            ],
        ),
    ]
