# Generated by Django 3.2 on 2021-05-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_rename_comptency_competency'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='description',
            field=models.CharField(default='testing', max_length=200),
            preserve_default=False,
        ),
    ]
